export const SmallDesktop = '(max-width: 1310px)'
export const MediaPlayerBreakPoint = '(max-width: 975px)'
export const iPad = '(max-width: 768px)'
export const CircleBreakPoint1 = '(max-width: 690)'
export const CircleBreakPoint2 = '(max-width: 650)'
export const ImageBreakPoint1 = '(max-width: 535)'
export const iPhone5 = '(max-width: 320px)'